type Party = {
	_id: string;
	acName?: string;
	cpName?: string;
	mobile?: string;
	phone?: string;
	email?: string;
	add1?: string;
	add2?: string;
	add3?: string;
	pin?: string;
	cin?: string;
	vat?: string;
	cst?: string;
	pan?: string;
	tan?: string;
	range?: string;
	tin?: string;
	ecc?: string;
	stregn?: string;
	state?: string;
	statecd?: string;
	gstin?: string;
	partyType: "RAW_MATERIAL_DEALER" | "LABOUR_JOB_WORKER";
	partySubType: { _id: string; name: string; description?: string } | string;
	isDeleted: boolean;
	createdAt: string;
	updatedAt: string;
};
